name: project_apk_catatan_keuangan
description: "This Financial Records app was created to assist users in recording their daily financial activities, both expenses and income. The app also provides monthly, weekly, and yearly reports, so users can better track and manage their finances."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_charts: ^27.1.58
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  material_symbols_icons: ^4.2800.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/images/
  
  fonts:
    - family: Poppins_Light
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
    - family: Poppins_Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Poppins_Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: Poppins_SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf

    - family: Poppins_Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

  uses-material-design: true
